version: '3.8'
services:
  server:
    build: .
    container_name: nest-server
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - MONGO_CONNECTION_URL=${MONGO_CONNECTION_URL}
    volumes:
      - .:/app
    command: npm run start:prod

  mongo:
    image: mongo:7
    container_name: mongo-db
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
